# [문제] BMI 지수 계산 및 과체중 이상인 BMI 값 확인
- 10명에 대한 키와 몸무게가 들어있는 'height_weight.txt'를 읽어 각 사람별 BMI 지수를 구하고 비만 전단계 이상인 BMI 값 확인하기

<pre>
 BMI 지수 = 몸무게(kg) / 키(M)의 제곱
 체질량지수의 범위 값에 따른 비만도 값 지정
 18.5 미만 ▶ 저체중
 18.5 ~ 22.9 ▶ 정상
 23 ~ 24.9 ▶ 비만 전단계
 25 ~ 29 ▶ 1단계 비만
 30 ~ 34.9 ▶ 2단계 비만
 35이상 ▶ 고도비만
</pre>

In [2]:
import numpy as np

# np.loadtxt() 데이터를 불러오는 함수
# delimiter : 구분자 콤마,
# dtype : 데이터 타입
data = np.loadtxt('height_weight.txt', delimiter=',', dtype=float)
# print(data)
# print(type(data)) #ndarray

height = data[0]
weight = data[1]
# print(height)
# print(weight)

BMI = weight / ((height/100) ** 2)
print('각 사람별 BMI 지수: ', BMI)

# print(BMI>=23)
print('비만 전단계 이상인 BMI 값 확인하기: ', BMI[BMI>=23])
# 비만 전단계 이상인 BMI 값 확인하기

각 사람별 BMI 지수:  [21.37153104 27.07018468 25.86122449 24.20652885 16.03543423 20.14486193
 23.14392095 21.69720651 23.62028791 25.59220998]
비만 전단계 이상인 BMI 값 확인하기:  [27.07018468 25.86122449 24.20652885 23.14392095 23.62028791 25.59220998]


In [34]:
# A.
weight = data[1]
print(weight)

# 키를 미터 단위로 바꾸고 제곱
squared_height_m = (data[0]/100) **2
print(squared_height_m)

bmi = weight / squared_height_m
print(bmi)

print(bmi[bmi>=23])

[65.6 88.  79.2 69.3 55.  71.2 73.  68.9 74.  82. ]
[3.069504 3.250809 3.0625   2.862864 3.429904 3.5344   3.154176 3.175524
 3.1329   3.2041  ]
[21.37153104 27.07018468 25.86122449 24.20652885 16.03543423 20.14486193
 23.14392095 21.69720651 23.62028791 25.59220998]
[27.07018468 25.86122449 24.20652885 23.14392095 23.62028791 25.59220998]


# [문제] 국가건강검진 혈압혈당 데이터 분석

* '국가건강검진_혈압혈당데이터.csv' 파일 내용을 읽기 <data = np.loadtxt("국가건강검진_혈압혈당데이터.csv", delimiter=",", dtype=np.float, skiprows=1)>
    - 성별: 1(남자), 2(여자)
    - 연령그룹: 1(20-24), 2(25-26),...25-74세까지 2살 간격으로 1개 그룹으로 지정, 27(74세 이상)
    - 고혈압 당뇨병 진료여부: 1(고혈압 및 당뇨진료내역 있음), 2(고혈압 진료내역 있음), 3(당뇨 진료내역 있음), 4(고혈압 및 당뇨 진료내역 없음)
    - 정상혈압: 수축기 혈압 120nnHg 미만, 확장기 혈압 80mmHg 미만
    - 공복혈당 수치: 126 mg/dL 이상 -> 당뇨병, 100mg/dL-> 정상
* 전체 레코드 수와 상위 5개 데이터 확인
* 데이터 모양 확인
* 여성과 남성의 데이터 수 확인
* 여성과 남성의 수축기혈압과 이완기혈압의 평균값 확인
* 정상 혈압 남자 및 여자 수 확인
* 당뇨병 질환(공복혈당 수치 126mg/dL 이상)을 가지고 있는 사람들의 평균 체질량지수

In [99]:
import numpy as np

data = np.loadtxt("국가건강검진_혈압혈당데이터.csv", delimiter=",", dtype=np.float64, skiprows=1)
# print(data)

print(f'전체 레코드 수: {len(data):,}개') #1,000,000
print('상위 5개 데이터: ', data[0:5])
print('데이터 모양 확인: ', data.shape) #(1000000, 7)

# 여성과 남성의 데이터 수 확인
gender = data[:,[0]]
print('남성 데이터 수: ', np.sum(data[:,[0]] == 1))
print('여성 데이터 수: ', np.sum(data[:,[0]] == 2))

# 여성과 남성의 수축기혈압과 이완기혈압의 평균값 확인
cp = data[:,[2]]
rp = data[:,[3]]

con1 = np.where(gender==1)
# print(con1)
# print(cp[con1])
print('남성 수축기혈압 평균:', np.mean(cp[con1]))
print('남성 이완기혈압 평균:', np.mean(rp[con1]))

con2 = np.where(gender==2)
# print(con2)
# print(cp[con2])
print('여성 수축기혈압 평균:', np.mean(cp[con2]))
print('여성 이완기혈압 평균:', np.mean(rp[con2]))


# 정상 혈압 남자 및 여자 수 확인
# 정상혈압: 수축기 혈압 120nnHg 미만, 확장기 혈압 80mmHg 미만
con1 = np.logical_and(gender == 1, cp<120, rp<80)
con2 = np.logical_and(gender == 2, cp<120, rp<80)
print('정상 혈압 남자 수: ', np.sum(con1))
print('정상 혈압 여자 수: ', np.sum(con2))

# 당뇨병 질환(공복혈당 수치 126mg/dL 이상)을 가지고 있는 사람들의 평균 체질량지수
# 공복혈당 수치: 126 mg/dL 이상 -> 당뇨병, 100mg/dL-> 정상
vb = data[:,[4]]
che = data[:,[6]]
con4 = np.where(vb>=126)
print('당뇨병 질환자의 평균 체질량지수:', np.mean(vb[con4]))

전체 레코드 수: 1,000,000개
상위 5개 데이터:  [[  1.    1.  116.   78.   94.    4.   16.6]
 [  1.    1.  100.   60.   79.    4.   22.3]
 [  1.    1.  100.   60.   87.    4.   21.9]
 [  1.    1.  111.   70.   72.    4.   20.2]
 [  1.    1.  120.   80.   98.    4.   20. ]]
데이터 모양 확인:  (1000000, 7)
남성 데이터 수:  510227
여성 데이터 수:  489773
남성 수축기혈압 평균: 124.2799538244742
남성 이완기혈압 평균: 77.61497725522169
여성 수축기혈압 평균: 119.36300081874664
여성 이완기혈압 평균: 73.88446688567969
정상 혈압 남자 수:  173595
정상 혈압 여자 수:  245583
당뇨병 질환자의 평균 체질량지수: 160.6845843786115


In [ ]:
# A.
import numpy as np

data = np.loadtxt("국가건강검진_혈압혈당데이터.csv", delimiter=",", dtype=np.float64, skiprows=1)
# skiprows : 컬럼명

print(f'전체 레코드 수: {len(data):,}개') #1,000,000
print('상위 5개 데이터: ', data[:5])
print('데이터 모양 확인: ', data.shape) #(1000000, 7)

In [102]:
# 각 컬럼별 unique값 확인
print('성별 값: ', np.unique(data[:,0]))
print('고혈압 당뇨병 진료여부 값: ', np.unique(data[:,5]))

성별 값:  [1. 2.]
고혈압 당뇨병 진료여부:  [1. 2. 3. 4.]


In [104]:
# 여성과 남성의 데이터 수 확인
print(f'남성 데이터 수: {sum(data[:,0] == 1):,}개')
print(f'여성 데이터 수: {sum(data[:,0] == 2):,}개')

남성 데이터 수: 510,227개
여성 데이터 수: 489,773개


In [105]:
# 여성과 남성의 수축기혈압과 이완기혈압의 평균값 확인


# 수축기혈압 : SBP
male_sbp_mean = np.mean(data[data[:,0]==1][:,2])
# 모든 데이터 중 0번째 열이 1인 것의 모든 데이터 중 2번째 열의 평균
print(f'남성의 수축기 평균 혈압: {male_sbp_mean:.2f}') # 소수점 두 자리

female_sbp_mean = np.mean(data[data[:,0]==2][:,2])
# 모든 데이터 중 0번째 열이 2인 것의 모든 데이터 중 2번째 열의 평균
print(f'여성의 수축기 평균 혈압: {female_sbp_mean:.2f}')


# 이완기혈압 : DBP
male_dbp_mean = np.mean(data[data[:,0]==1][:,3])
# 모든 데이터 중 0번째 열이 1인 것의 모든 데이터 중 3번째 열의 평균
print(f'남성의 이완기 평균 혈압: {male_dbp_mean:.2f}')

female_dbp_mean = np.mean(data[data[:,0]==2][:,3])
# 모든 데이터 중 0번째 열이 2인 것의 모든 데이터 중 3번째 열의 평균
print(f'여성의 이완기 평균 혈압: {female_dbp_mean:.2f}')

남성의 수축기 평균 혈압: 124.28
여성의 수축기 평균 혈압: 119.36
남성의 이완기 평균 혈압: 77.61
여성의 이완기 평균 혈압: 73.88


In [108]:
# 정상 혈압 남자 및 여자 수 확인
# 정상혈압: 수축기 혈압 120nnHg 미만, 확장기 혈압 80mmHg 미만

nbp_masking = np.logical_and(data[:,2] < 120, data[:,3] < 80)
nbp = data[nbp_masking]

print(f'정상 혈압 남자 수: {sum(nbp[:,0]==1):,}')
print(f'정상 혈압 여자 수: {sum(nbp[:,0]==2):,}')

정상 혈압 남자 수: 158,007
정상 혈압 여자 수: 230,707


In [110]:
# 당뇨병 질환(공복혈당 수치 126mg/dL 이상)을 가지고 있는 사람들의 평균 체질량지수
# 공복혈당 수치: 126 mg/dL 이상 -> 당뇨병, 100mg/dL-> 정상

disease = data[data[:,4] >= 126]
print(f'당뇨병 질환 환자 평균 BMI: {np.mean(disease[:,6]):.2f}')

당뇨병 질환 환자 평균 BMI: 25.17


# [문제] 시에틀 강수량 데이터 분석
- 'Seattle2014.csv' 파일 내용 읽기
- 강수량('PRCP')이 많은 날 상위 10일 확인
- 1월 강수량만 출력
- 1월에 내린 강수량의 합, 평균강수량 확인
- 1년동안 강수량이 40미만으로 내린 날이 몇일인가?

In [80]:
import numpy as np

data = np.loadtxt('Seattle2014.csv', delimiter=',', dtype=object, skiprows=1)
# numpy에서는 모든 데이터 타입이 동일해야하는데
# seattle에는 숫자와 문자 데이터가 혼합되어있다
# 따라서 모든 데이터를 문자열로 읽어오기 위해 dtype=object로 지정
print(type(data))

<class 'numpy.ndarray'>


In [135]:
# 강수량('PRCP')이 많은 날 상위 10일 확인
prcp = np.array(data[:,3], np.int32)
# print(prcp)
prcp_sort = np.sort(prcp)[::-1]
# print(prcp_sort)
masking = np.argsort(prcp_sort)[:10]
# print(masking)

print(f'강수량 상위 10일: {data[:,2][masking]}')

상위 10일: ['20140702' '20140905' '20140904' '20140903' '20140902' '20140901'
 '20140831' '20140830' '20140829' '20140906']


In [218]:
# 1월 강수량만 출력
date = np.array(data[:,2], np.int64)
# print(date)
jan = date[0:31]
# print(jan)

print(f'1월 강수량: {prcp[0:31]}')

1월 강수량: [  0  41  15   0   0   3 122  97  58  43 213  15   0   0   0   0   0   0
   0   0   0   5   0   0   0   0   0  89 216   0  23]


In [223]:
# 1월에 내린 강수량의 합, 평균강수량 확인
print(f'1월 강수량의 합: {np.sum(prcp[0:31])}')
print(f'1월 평균 강수량: {np.mean(prcp[0:31])}')

1월 강수량의 합: 940
1월 평균 강수량: 30.322580645161292


In [242]:
# 1년동안 강수량이 40미만으로 내린 날이 몇일인가?

print(len(prcp[prcp < 40]))

277


In [57]:
# A.

# 강수량('PRCP')이 많은 날 상위 10일 확인
prcp_data = data[:,3].astype(np.int32)
print(np.sort(prcp_data)[::-1][:10])

# 특정 컬럼을 기준으로 정렬하기
prcp_data = data[:,[2,3]].astype(int)
# print(prcp_data[:10])
print(prcp_data[prcp_data[:,1].argsort()][::-1][:10])
# prcp_data의 1번째 컬럼, 즉 강수량 데이터를 argsort하여 오름차순 정렬된 인덱스

[467 343 333 323 320 277 264 254 221 216]
[[20140305      467]
 [20141128      343]
 [20140503      333]
 [20140308      323]
 [20141022      320]
 [20140316      277]
 [20140216      264]
 [20141030      254]
 [20140328      221]
 [20140129      216]]


In [238]:
# A.

# 1월 강수량만 출력
prcp_data = data[:,[2,3]] # 문자열로 가져옴
# print(prcp_data[:5])

temp = np.array( [ [date[4:6], prcp] for date, prcp in prcp_data ] )
# print(temp[:5])

jan_prcp = temp [temp[:,0]=='01'][:,1].astype(int)
# boolean indexing : temp의 모든 레코드 중에서 첫번째 컬럼이 01인 것만 인덱싱
# [:,1] : 날짜값 버리고 강수량만 보겠다
# int로 형변환
print(jan_prcp)

[  0  41  15   0   0   3 122  97  58  43 213  15   0   0   0   0   0   0
   0   0   0   5   0   0   0   0   0  89 216   0  23]


In [240]:
# A.

# 1월에 내린 강수량의 합, 평균강수량 확인
print(f'1월 강수량의 합: {np.sum(jan_prcp)}')
print(f'1월 평균 강수량: {np.mean(jan_prcp):.2f}')

1월 강수량의 합: 940
1월 평균 강수량: 30.32


In [241]:
# A.

# 1년동안 강수량이 40미만으로 내린 날이 몇일인가?
prcp_data = data[:,3].astype(int)
under_40 = prcp_data[prcp_data <40]

print(f'강수량이 40미만으로 내린 날: {len(under_40)}일')
# boolean이 아니므로 sum이 아닌 len을 사용해야

강수량이 40미만으로 내린 날: 277일


# [문제] 영화 평점 분석
- 'ratings.dat' 파일 내용 읽기 (데이터 형식: user_id::item_id::rating::timestamp)
- 상위 10개 데이터 출력하기
- 데이터 정보 확인(크기, 차원)
- 전체 데이터 평점 구하기
- 사용자 아이디 1인 데이터 출력하기
- 사용자 아이디 1인 사람의 평점 평균 구하기
- 각 사용자별 평점 구하기 (사용자 ID 수집: ID컬럼에 대한 np.unique() 함수 적용)
- 각 사용자별 평균 평점이 4점 이상인 사용자 및 인원수 구하기

In [243]:
import numpy as np

data = np.loadtxt('ratings.dat', delimiter='::', dtype=int)

In [319]:
# 상위 10개 데이터 출력하기

print(data[:10])

[[        1      1193         5 978300760]
 [        1       661         3 978302109]
 [        1       914         3 978301968]
 [        1      3408         4 978300275]
 [        1      2355         5 978824291]
 [        1      1197         3 978302268]
 [        1      1287         5 978302039]
 [        1      2804         5 978300719]
 [        1       594         4 978302268]
 [        1       919         4 978301368]]


In [320]:
# 데이터 정보 확인(크기, 차원)

print('데이터 크기: ', data.shape)
print('데이터 차원: ',data.ndim)

데이터 크기:  (1000209, 4)
데이터 차원:  2


In [322]:
# 전체 데이터 평점 평균구하기
print(f'전체 사용자 평균 평점: {np.mean(data[:,2]):.2f}')

전체 사용자 평균 평점: 3.58


In [323]:
# 사용자 아이디 1인 데이터 출력하기
user_1 = data[data[:,0]==1]
print(user_1)

[[        1      1193         5 978300760]
 [        1       661         3 978302109]
 [        1       914         3 978301968]
 [        1      3408         4 978300275]
 [        1      2355         5 978824291]
 [        1      1197         3 978302268]
 [        1      1287         5 978302039]
 [        1      2804         5 978300719]
 [        1       594         4 978302268]
 [        1       919         4 978301368]
 [        1       595         5 978824268]
 [        1       938         4 978301752]
 [        1      2398         4 978302281]
 [        1      2918         4 978302124]
 [        1      1035         5 978301753]
 [        1      2791         4 978302188]
 [        1      2687         3 978824268]
 [        1      2018         4 978301777]
 [        1      3105         5 978301713]
 [        1      2797         4 978302039]
 [        1      2321         3 978302205]
 [        1       720         3 978300760]
 [        1      1270         5 978300055]
 [        1

In [324]:
# 사용자 아이디 1인 사람의 평점 평균 구하기

user_1 = data[data[:,0]==1]
print(np.mean(user_1[:,2]))

4.188679245283019


In [333]:
# 각 사용자별 평점 평균 구하기 (사용자 ID 수집: ID컬럼에 대한 np.unique() 함수 적용)
user_ids = np.unique(data[:,0])
print(f'전체 사용자 수: {len(user_ids):,}명')

for user, rate in data[:,[0,2]]:
    for unq_user in np.unique(data[:,0]):
        mn = np.mean(data[data[:,0]==unq_user][:,2] )
        print(f'{unq_user}번 평점 평균: {mn:.2f}')

전체 사용자 수: 6,040명
1번 평점 평균: 4.19
2번 평점 평균: 3.71
3번 평점 평균: 3.90
4번 평점 평균: 4.19
5번 평점 평균: 3.15
6번 평점 평균: 3.90
7번 평점 평균: 4.32
8번 평점 평균: 3.88
9번 평점 평균: 3.74
10번 평점 평균: 4.11
11번 평점 평균: 3.28
12번 평점 평균: 3.83
13번 평점 평균: 3.39
14번 평점 평균: 3.32
15번 평점 평균: 3.32
16번 평점 평균: 3.03
17번 평점 평균: 4.08
18번 평점 평균: 3.65
19번 평점 평균: 3.57
20번 평점 평균: 4.08
21번 평점 평균: 2.91
22번 평점 평균: 3.07
23번 평점 평균: 3.32
24번 평점 평균: 3.95
25번 평점 평균: 3.74
26번 평점 평균: 2.96
27번 평점 평균: 4.17
28번 평점 평균: 3.76
29번 평점 평균: 3.58
30번 평점 평균: 3.49
31번 평점 평균: 3.73
32번 평점 평균: 3.62
33번 평점 평균: 3.50
34번 평점 평균: 3.87
35번 평점 평균: 3.54
36번 평점 평균: 4.20
37번 평점 평균: 3.70
38번 평점 평균: 3.58
39번 평점 평균: 3.56
40번 평점 평균: 3.45
41번 평점 평균: 3.48
42번 평점 평균: 3.74
43번 평점 평균: 4.12
44번 평점 평균: 3.63
45번 평점 평균: 2.95
46번 평점 평균: 4.22
47번 평점 평균: 3.91
48번 평점 평균: 3.07
49번 평점 평균: 3.71
50번 평점 평균: 3.07
51번 평점 평균: 3.83
52번 평점 평균: 3.56
53번 평점 평균: 4.24
54번 평점 평균: 4.03
55번 평점 평균: 4.12
56번 평점 평균: 3.97
57번 평점 평균: 2.91
58번 평점 평균: 3.97
59번 평점 평균: 3.47
60번 평점 평균: 3.41
61번 평점 평균: 2.78
62번 평점 평균: 3.57


508번 평점 평균: 3.32
509번 평점 평균: 3.31
510번 평점 평균: 3.83
511번 평점 평균: 3.74
512번 평점 평균: 3.84
513번 평점 평균: 3.15
514번 평점 평균: 4.20
515번 평점 평균: 3.73
516번 평점 평균: 2.93
517번 평점 평균: 3.96
518번 평점 평균: 4.35
519번 평점 평균: 3.38
520번 평점 평균: 3.94
521번 평점 평균: 4.29
522번 평점 평균: 3.84
523번 평점 평균: 4.06
524번 평점 평균: 3.61
525번 평점 평균: 4.03
526번 평점 평균: 3.90
527번 평점 평균: 4.08
528번 평점 평균: 3.36
529번 평점 평균: 4.20
530번 평점 평균: 4.00
531번 평점 평균: 3.16
532번 평점 평균: 3.86
533번 평점 평균: 3.34
534번 평점 평균: 3.75
535번 평점 평균: 3.57
536번 평점 평균: 3.94
537번 평점 평균: 4.31
538번 평점 평균: 4.46
539번 평점 평균: 3.92
540번 평점 평균: 3.23
541번 평점 평균: 3.19
542번 평점 평균: 3.76
543번 평점 평균: 4.08
544번 평점 평균: 3.78
545번 평점 평균: 3.48
546번 평점 평균: 3.23
547번 평점 평균: 3.86
548번 평점 평균: 3.09
549번 평점 평균: 3.76
550번 평점 평균: 3.58
551번 평점 평균: 3.82
552번 평점 평균: 3.76
553번 평점 평균: 4.16
554번 평점 평균: 3.51
555번 평점 평균: 3.82
556번 평점 평균: 3.50
557번 평점 평균: 3.88
558번 평점 평균: 3.68
559번 평점 평균: 3.00
560번 평점 평균: 3.90
561번 평점 평균: 3.72
562번 평점 평균: 3.70
563번 평점 평균: 2.70
564번 평점 평균: 4.00
565번 평점 평균: 3.44
566번 평점 평균: 2.

1032번 평점 평균: 3.94
1033번 평점 평균: 3.29
1034번 평점 평균: 3.48
1035번 평점 평균: 3.82
1036번 평점 평균: 4.32
1037번 평점 평균: 3.58
1038번 평점 평균: 3.93
1039번 평점 평균: 2.89
1040번 평점 평균: 4.24
1041번 평점 평균: 4.32
1042번 평점 평균: 2.76
1043번 평점 평균: 3.92
1044번 평점 평균: 3.76
1045번 평점 평균: 3.54
1046번 평점 평균: 3.88
1047번 평점 평균: 3.88
1048번 평점 평균: 4.00
1049번 평점 평균: 3.58
1050번 평점 평균: 2.90
1051번 평점 평균: 3.47
1052번 평점 평균: 4.34
1053번 평점 평균: 3.34
1054번 평점 평균: 3.89
1055번 평점 평균: 3.45
1056번 평점 평균: 3.47
1057번 평점 평균: 3.73
1058번 평점 평균: 3.80
1059번 평점 평균: 2.89
1060번 평점 평균: 3.35
1061번 평점 평균: 3.98
1062번 평점 평균: 4.48
1063번 평점 평균: 4.18
1064번 평점 평균: 3.71
1065번 평점 평균: 3.72
1066번 평점 평균: 3.53
1067번 평점 평균: 3.97
1068번 평점 평균: 3.73
1069번 평점 평균: 2.87
1070번 평점 평균: 3.62
1071번 평점 평균: 4.43
1072번 평점 평균: 4.05
1073번 평점 평균: 4.15
1074번 평점 평균: 3.45
1075번 평점 평균: 4.05
1076번 평점 평균: 3.24
1077번 평점 평균: 4.02
1078번 평점 평균: 3.98
1079번 평점 평균: 3.59
1080번 평점 평균: 3.74
1081번 평점 평균: 4.15
1082번 평점 평균: 4.33
1083번 평점 평균: 2.69
1084번 평점 평균: 3.15
1085번 평점 평균: 3.71
1086번 평점 평균: 3.86
1087번 평점 평

1531번 평점 평균: 3.46
1532번 평점 평균: 4.10
1533번 평점 평균: 3.84
1534번 평점 평균: 3.62
1535번 평점 평균: 3.90
1536번 평점 평균: 4.22
1537번 평점 평균: 3.76
1538번 평점 평균: 3.99
1539번 평점 평균: 4.37
1540번 평점 평균: 3.81
1541번 평점 평균: 4.42
1542번 평점 평균: 3.67
1543번 평점 평균: 3.46
1544번 평점 평균: 3.69
1545번 평점 평균: 3.10
1546번 평점 평균: 3.75
1547번 평점 평균: 3.93
1548번 평점 평균: 3.58
1549번 평점 평균: 3.62
1550번 평점 평균: 3.93
1551번 평점 평균: 3.94
1552번 평점 평균: 3.69
1553번 평점 평균: 3.72
1554번 평점 평균: 3.81
1555번 평점 평균: 4.35
1556번 평점 평균: 3.21
1557번 평점 평균: 3.98
1558번 평점 평균: 4.12
1559번 평점 평균: 3.59
1560번 평점 평균: 3.49
1561번 평점 평균: 4.01
1562번 평점 평균: 2.87
1563번 평점 평균: 3.81
1564번 평점 평균: 3.06
1565번 평점 평균: 3.74
1566번 평점 평균: 3.50
1567번 평점 평균: 3.89
1568번 평점 평균: 4.00
1569번 평점 평균: 4.59
1570번 평점 평균: 3.55
1571번 평점 평균: 3.95
1572번 평점 평균: 3.18
1573번 평점 평균: 3.69
1574번 평점 평균: 3.60
1575번 평점 평균: 3.87
1576번 평점 평균: 3.88
1577번 평점 평균: 4.10
1578번 평점 평균: 4.16
1579번 평점 평균: 3.45
1580번 평점 평균: 3.54
1581번 평점 평균: 3.22
1582번 평점 평균: 3.64
1583번 평점 평균: 3.73
1584번 평점 평균: 3.33
1585번 평점 평균: 3.61
1586번 평점 평

2032번 평점 평균: 3.68
2033번 평점 평균: 2.61
2034번 평점 평균: 4.22
2035번 평점 평균: 3.57
2036번 평점 평균: 3.94
2037번 평점 평균: 3.45
2038번 평점 평균: 3.82
2039번 평점 평균: 3.58
2040번 평점 평균: 3.37
2041번 평점 평균: 3.55
2042번 평점 평균: 3.14
2043번 평점 평균: 2.57
2044번 평점 평균: 4.12
2045번 평점 평균: 4.04
2046번 평점 평균: 3.59
2047번 평점 평균: 3.59
2048번 평점 평균: 4.14
2049번 평점 평균: 4.11
2050번 평점 평균: 3.90
2051번 평점 평균: 3.43
2052번 평점 평균: 2.90
2053번 평점 평균: 3.40
2054번 평점 평균: 3.41
2055번 평점 평균: 4.17
2056번 평점 평균: 4.10
2057번 평점 평균: 3.86
2058번 평점 평균: 3.32
2059번 평점 평균: 3.55
2060번 평점 평균: 3.12
2061번 평점 평균: 4.30
2062번 평점 평균: 4.15
2063번 평점 평균: 2.95
2064번 평점 평균: 4.00
2065번 평점 평균: 4.45
2066번 평점 평균: 4.07
2067번 평점 평균: 3.57
2068번 평점 평균: 3.95
2069번 평점 평균: 3.91
2070번 평점 평균: 4.41
2071번 평점 평균: 3.41
2072번 평점 평균: 4.00
2073번 평점 평균: 3.70
2074번 평점 평균: 3.47
2075번 평점 평균: 3.33
2076번 평점 평균: 3.48
2077번 평점 평균: 3.23
2078번 평점 평균: 3.74
2079번 평점 평균: 3.47
2080번 평점 평균: 4.28
2081번 평점 평균: 3.12
2082번 평점 평균: 4.34
2083번 평점 평균: 4.35
2084번 평점 평균: 3.95
2085번 평점 평균: 3.66
2086번 평점 평균: 3.70
2087번 평점 평

2553번 평점 평균: 4.13
2554번 평점 평균: 4.02
2555번 평점 평균: 3.60
2556번 평점 평균: 3.49
2557번 평점 평균: 3.65
2558번 평점 평균: 3.56
2559번 평점 평균: 3.84
2560번 평점 평균: 4.12
2561번 평점 평균: 3.78
2562번 평점 평균: 3.86
2563번 평점 평균: 2.96
2564번 평점 평균: 3.77
2565번 평점 평균: 3.72
2566번 평점 평균: 3.36
2567번 평점 평균: 3.49
2568번 평점 평균: 3.42
2569번 평점 평균: 3.46
2570번 평점 평균: 3.81
2571번 평점 평균: 4.07
2572번 평점 평균: 4.19
2573번 평점 평균: 4.01
2574번 평점 평균: 4.61
2575번 평점 평균: 3.73
2576번 평점 평균: 3.08
2577번 평점 평균: 3.15
2578번 평점 평균: 4.14
2579번 평점 평균: 4.16
2580번 평점 평균: 3.70
2581번 평점 평균: 4.05
2582번 평점 평균: 4.00
2583번 평점 평균: 4.34
2584번 평점 평균: 3.70
2585번 평점 평균: 3.71
2586번 평점 평균: 4.12
2587번 평점 평균: 4.03
2588번 평점 평균: 3.80
2589번 평점 평균: 3.52
2590번 평점 평균: 3.20
2591번 평점 평균: 3.80
2592번 평점 평균: 3.63
2593번 평점 평균: 4.54
2594번 평점 평균: 3.11
2595번 평점 평균: 3.35
2596번 평점 평균: 3.76
2597번 평점 평균: 3.88
2598번 평점 평균: 3.70
2599번 평점 평균: 3.62
2600번 평점 평균: 2.98
2601번 평점 평균: 3.79
2602번 평점 평균: 3.34
2603번 평점 평균: 3.88
2604번 평점 평균: 3.90
2605번 평점 평균: 3.94
2606번 평점 평균: 4.22
2607번 평점 평균: 4.18
2608번 평점 평

3072번 평점 평균: 3.38
3073번 평점 평균: 4.54
3074번 평점 평균: 4.30
3075번 평점 평균: 3.63
3076번 평점 평균: 3.82
3077번 평점 평균: 3.85
3078번 평점 평균: 4.06
3079번 평점 평균: 3.88
3080번 평점 평균: 3.88
3081번 평점 평균: 4.04
3082번 평점 평균: 3.37
3083번 평점 평균: 3.85
3084번 평점 평균: 3.71
3085번 평점 평균: 4.17
3086번 평점 평균: 4.22
3087번 평점 평균: 3.92
3088번 평점 평균: 4.02
3089번 평점 평균: 4.34
3090번 평점 평균: 3.65
3091번 평점 평균: 3.75
3092번 평점 평균: 4.02
3093번 평점 평균: 3.80
3094번 평점 평균: 3.66
3095번 평점 평균: 3.90
3096번 평점 평균: 4.11
3097번 평점 평균: 3.63
3098번 평점 평균: 3.37
3099번 평점 평균: 3.28
3100번 평점 평균: 4.20
3101번 평점 평균: 4.15
3102번 평점 평균: 3.44
3103번 평점 평균: 4.13
3104번 평점 평균: 3.90
3105번 평점 평균: 3.99
3106번 평점 평균: 4.16
3107번 평점 평균: 3.56
3108번 평점 평균: 3.69
3109번 평점 평균: 3.53
3110번 평점 평균: 3.60
3111번 평점 평균: 3.24
3112번 평점 평균: 3.39
3113번 평점 평균: 3.68
3114번 평점 평균: 3.34
3115번 평점 평균: 3.42
3116번 평점 평균: 3.64
3117번 평점 평균: 4.30
3118번 평점 평균: 3.54
3119번 평점 평균: 3.38
3120번 평점 평균: 3.62
3121번 평점 평균: 3.47
3122번 평점 평균: 3.11
3123번 평점 평균: 3.56
3124번 평점 평균: 3.42
3125번 평점 평균: 3.73
3126번 평점 평균: 3.77
3127번 평점 평

3574번 평점 평균: 3.64
3575번 평점 평균: 3.32
3576번 평점 평균: 3.33
3577번 평점 평균: 3.73
3578번 평점 평균: 3.39
3579번 평점 평균: 3.32
3580번 평점 평균: 4.03
3581번 평점 평균: 3.24
3582번 평점 평균: 3.63
3583번 평점 평균: 4.20
3584번 평점 평균: 3.09
3585번 평점 평균: 3.69
3586번 평점 평균: 3.36
3587번 평점 평균: 4.35
3588번 평점 평균: 4.07
3589번 평점 평균: 2.49
3590번 평점 평균: 4.16
3591번 평점 평균: 3.71
3592번 평점 평균: 4.36
3593번 평점 평균: 3.39
3594번 평점 평균: 3.45
3595번 평점 평균: 4.00
3596번 평점 평균: 4.69
3597번 평점 평균: 3.97
3598번 평점 평균: 1.02
3599번 평점 평균: 3.45
3600번 평점 평균: 3.73
3601번 평점 평균: 4.13
3602번 평점 평균: 3.69
3603번 평점 평균: 2.80
3604번 평점 평균: 4.59
3605번 평점 평균: 3.95
3606번 평점 평균: 4.11
3607번 평점 평균: 3.44
3608번 평점 평균: 3.75
3609번 평점 평균: 3.16
3610번 평점 평균: 2.33
3611번 평점 평균: 4.03
3612번 평점 평균: 3.67
3613번 평점 평균: 3.86
3614번 평점 평균: 3.28
3615번 평점 평균: 3.43
3616번 평점 평균: 3.86
3617번 평점 평균: 3.62
3618번 평점 평균: 3.01
3619번 평점 평균: 3.68
3620번 평점 평균: 2.96
3621번 평점 평균: 3.11
3622번 평점 평균: 3.90
3623번 평점 평균: 3.68
3624번 평점 평균: 3.99
3625번 평점 평균: 3.28
3626번 평점 평균: 3.60
3627번 평점 평균: 3.64
3628번 평점 평균: 3.52
3629번 평점 평

4077번 평점 평균: 3.89
4078번 평점 평균: 3.39
4079번 평점 평균: 3.77
4080번 평점 평균: 4.18
4081번 평점 평균: 4.00
4082번 평점 평균: 3.95
4083번 평점 평균: 2.96
4084번 평점 평균: 4.34
4085번 평점 평균: 3.61
4086번 평점 평균: 4.49
4087번 평점 평균: 2.98
4088번 평점 평균: 3.29
4089번 평점 평균: 3.76
4090번 평점 평균: 3.81
4091번 평점 평균: 3.45
4092번 평점 평균: 4.15
4093번 평점 평균: 4.34
4094번 평점 평균: 4.17
4095번 평점 평균: 3.79
4096번 평점 평균: 3.34
4097번 평점 평균: 3.73
4098번 평점 평균: 3.86
4099번 평점 평균: 3.74
4100번 평점 평균: 4.14
4101번 평점 평균: 3.63
4102번 평점 평균: 2.79
4103번 평점 평균: 3.50
4104번 평점 평균: 3.53
4105번 평점 평균: 2.73
4106번 평점 평균: 3.00
4107번 평점 평균: 4.02
4108번 평점 평균: 4.34
4109번 평점 평균: 3.48
4110번 평점 평균: 4.33
4111번 평점 평균: 3.64
4112번 평점 평균: 4.04
4113번 평점 평균: 3.52
4114번 평점 평균: 3.80
4115번 평점 평균: 3.81
4116번 평점 평균: 3.79
4117번 평점 평균: 4.09
4118번 평점 평균: 4.06
4119번 평점 평균: 3.54
4120번 평점 평균: 3.38
4121번 평점 평균: 3.88
4122번 평점 평균: 3.54
4123번 평점 평균: 3.31
4124번 평점 평균: 3.42
4125번 평점 평균: 2.80
4126번 평점 평균: 3.51
4127번 평점 평균: 3.84
4128번 평점 평균: 4.00
4129번 평점 평균: 4.00
4130번 평점 평균: 3.68
4131번 평점 평균: 3.98
4132번 평점 평

4586번 평점 평균: 4.08
4587번 평점 평균: 2.77
4588번 평점 평균: 3.98
4589번 평점 평균: 4.59
4590번 평점 평균: 3.84
4591번 평점 평균: 3.25
4592번 평점 평균: 3.36
4593번 평점 평균: 3.37
4594번 평점 평균: 4.06
4595번 평점 평균: 4.59
4596번 평점 평균: 3.30
4597번 평점 평균: 3.41
4598번 평점 평균: 3.77
4599번 평점 평균: 4.06
4600번 평점 평균: 3.63
4601번 평점 평균: 3.62
4602번 평점 평균: 3.50
4603번 평점 평균: 3.73
4604번 평점 평균: 3.07
4605번 평점 평균: 3.19
4606번 평점 평균: 3.47
4607번 평점 평균: 3.89
4608번 평점 평균: 3.70
4609번 평점 평균: 3.01
4610번 평점 평균: 3.22
4611번 평점 평균: 3.28
4612번 평점 평균: 3.58
4613번 평점 평균: 4.05
4614번 평점 평균: 3.95
4615번 평점 평균: 3.55
4616번 평점 평균: 3.97
4617번 평점 평균: 3.16
4618번 평점 평균: 3.54
4619번 평점 평균: 3.44
4620번 평점 평균: 3.82
4621번 평점 평균: 3.46
4622번 평점 평균: 3.52
4623번 평점 평균: 3.97
4624번 평점 평균: 3.95
4625번 평점 평균: 3.42
4626번 평점 평균: 3.56
4627번 평점 평균: 3.89
4628번 평점 평균: 3.60
4629번 평점 평균: 3.38
4630번 평점 평균: 3.79
4631번 평점 평균: 3.60
4632번 평점 평균: 3.91
4633번 평점 평균: 3.98
4634번 평점 평균: 4.81
4635번 평점 평균: 3.75
4636번 평점 평균: 2.00
4637번 평점 평균: 3.58
4638번 평점 평균: 2.89
4639번 평점 평균: 4.29
4640번 평점 평균: 2.66
4641번 평점 평

5097번 평점 평균: 3.99
5098번 평점 평균: 3.15
5099번 평점 평균: 3.89
5100번 평점 평균: 4.18
5101번 평점 평균: 2.49
5102번 평점 평균: 4.52
5103번 평점 평균: 4.34
5104번 평점 평균: 4.24
5105번 평점 평균: 3.11
5106번 평점 평균: 3.86
5107번 평점 평균: 3.21
5108번 평점 평균: 3.39
5109번 평점 평균: 3.74
5110번 평점 평균: 4.32
5111번 평점 평균: 3.63
5112번 평점 평균: 3.06
5113번 평점 평균: 2.54
5114번 평점 평균: 3.77
5115번 평점 평균: 4.38
5116번 평점 평균: 4.33
5117번 평점 평균: 3.14
5118번 평점 평균: 3.05
5119번 평점 평균: 3.92
5120번 평점 평균: 3.76
5121번 평점 평균: 3.45
5122번 평점 평균: 4.48
5123번 평점 평균: 3.28
5124번 평점 평균: 3.53
5125번 평점 평균: 4.24
5126번 평점 평균: 3.96
5127번 평점 평균: 3.20
5128번 평점 평균: 3.86
5129번 평점 평균: 3.79
5130번 평점 평균: 4.39
5131번 평점 평균: 3.40
5132번 평점 평균: 4.34
5133번 평점 평균: 3.08
5134번 평점 평균: 3.72
5135번 평점 평균: 3.87
5136번 평점 평균: 3.75
5137번 평점 평균: 4.13
5138번 평점 평균: 3.25
5139번 평점 평균: 3.53
5140번 평점 평균: 3.40
5141번 평점 평균: 3.98
5142번 평점 평균: 3.57
5143번 평점 평균: 4.02
5144번 평점 평균: 3.81
5145번 평점 평균: 3.25
5146번 평점 평균: 3.37
5147번 평점 평균: 3.59
5148번 평점 평균: 3.87
5149번 평점 평균: 4.03
5150번 평점 평균: 3.69
5151번 평점 평균: 2.78
5152번 평점 평

5568번 평점 평균: 4.04
5569번 평점 평균: 3.41
5570번 평점 평균: 3.85
5571번 평점 평균: 3.46
5572번 평점 평균: 3.80
5573번 평점 평균: 3.80
5574번 평점 평균: 3.72
5575번 평점 평균: 2.97
5576번 평점 평균: 3.89
5577번 평점 평균: 3.31
5578번 평점 평균: 3.96
5579번 평점 평균: 4.21
5580번 평점 평균: 3.87
5581번 평점 평균: 4.30
5582번 평점 평균: 4.60
5583번 평점 평균: 3.88
5584번 평점 평균: 3.57
5585번 평점 평균: 3.76
5586번 평점 평균: 4.07
5587번 평점 평균: 3.93
5588번 평점 평균: 3.78
5589번 평점 평균: 4.42
5590번 평점 평균: 3.64
5591번 평점 평균: 4.26
5592번 평점 평균: 4.04
5593번 평점 평균: 4.35
5594번 평점 평균: 4.08
5595번 평점 평균: 3.15
5596번 평점 평균: 4.08
5597번 평점 평균: 3.18
5598번 평점 평균: 3.87
5599번 평점 평균: 3.37
5600번 평점 평균: 3.91
5601번 평점 평균: 3.44
5602번 평점 평균: 4.00
5603번 평점 평균: 2.31
5604번 평점 평균: 3.52
5605번 평점 평균: 3.00
5606번 평점 평균: 3.83
5607번 평점 평균: 3.52
5608번 평점 평균: 3.75
5609번 평점 평균: 4.67
5610번 평점 평균: 4.20
5611번 평점 평균: 4.26
5612번 평점 평균: 2.97
5613번 평점 평균: 3.64
5614번 평점 평균: 3.81
5615번 평점 평균: 3.46
5616번 평점 평균: 3.85
5617번 평점 평균: 3.54
5618번 평점 평균: 3.90
5619번 평점 평균: 3.65
5620번 평점 평균: 3.42
5621번 평점 평균: 3.03
5622번 평점 평균: 4.13
5623번 평점 평

6026번 평점 평균: 3.62
6027번 평점 평균: 4.25
6028번 평점 평균: 3.45
6029번 평점 평균: 3.90
6030번 평점 평균: 3.94
6031번 평점 평균: 3.67
6032번 평점 평균: 4.13
6033번 평점 평균: 3.85
6034번 평점 평균: 4.10
6035번 평점 평균: 2.61
6036번 평점 평균: 3.30
6037번 평점 평균: 3.72
6038번 평점 평균: 3.80
6039번 평점 평균: 3.88
6040번 평점 평균: 3.58
1번 평점 평균: 4.19
2번 평점 평균: 3.71
3번 평점 평균: 3.90
4번 평점 평균: 4.19
5번 평점 평균: 3.15
6번 평점 평균: 3.90
7번 평점 평균: 4.32
8번 평점 평균: 3.88
9번 평점 평균: 3.74
10번 평점 평균: 4.11
11번 평점 평균: 3.28
12번 평점 평균: 3.83
13번 평점 평균: 3.39
14번 평점 평균: 3.32
15번 평점 평균: 3.32
16번 평점 평균: 3.03
17번 평점 평균: 4.08
18번 평점 평균: 3.65
19번 평점 평균: 3.57
20번 평점 평균: 4.08
21번 평점 평균: 2.91
22번 평점 평균: 3.07
23번 평점 평균: 3.32
24번 평점 평균: 3.95
25번 평점 평균: 3.74
26번 평점 평균: 2.96
27번 평점 평균: 4.17
28번 평점 평균: 3.76
29번 평점 평균: 3.58
30번 평점 평균: 3.49
31번 평점 평균: 3.73
32번 평점 평균: 3.62
33번 평점 평균: 3.50
34번 평점 평균: 3.87
35번 평점 평균: 3.54
36번 평점 평균: 4.20
37번 평점 평균: 3.70
38번 평점 평균: 3.58
39번 평점 평균: 3.56
40번 평점 평균: 3.45
41번 평점 평균: 3.48
42번 평점 평균: 3.74
43번 평점 평균: 4.12
44번 평점 평균: 3.63
45번 평점 평균: 2.95
46번 평점 평균: 4.22
47번

496번 평점 평균: 4.29
497번 평점 평균: 3.58
498번 평점 평균: 3.65
499번 평점 평균: 3.97
500번 평점 평균: 3.63
501번 평점 평균: 3.42
502번 평점 평균: 4.08
503번 평점 평균: 4.45
504번 평점 평균: 3.81
505번 평점 평균: 4.22
506번 평점 평균: 3.42
507번 평점 평균: 3.95
508번 평점 평균: 3.32
509번 평점 평균: 3.31
510번 평점 평균: 3.83
511번 평점 평균: 3.74
512번 평점 평균: 3.84
513번 평점 평균: 3.15
514번 평점 평균: 4.20
515번 평점 평균: 3.73
516번 평점 평균: 2.93
517번 평점 평균: 3.96
518번 평점 평균: 4.35
519번 평점 평균: 3.38
520번 평점 평균: 3.94
521번 평점 평균: 4.29
522번 평점 평균: 3.84
523번 평점 평균: 4.06
524번 평점 평균: 3.61
525번 평점 평균: 4.03
526번 평점 평균: 3.90
527번 평점 평균: 4.08
528번 평점 평균: 3.36
529번 평점 평균: 4.20
530번 평점 평균: 4.00
531번 평점 평균: 3.16
532번 평점 평균: 3.86
533번 평점 평균: 3.34
534번 평점 평균: 3.75
535번 평점 평균: 3.57
536번 평점 평균: 3.94
537번 평점 평균: 4.31
538번 평점 평균: 4.46
539번 평점 평균: 3.92
540번 평점 평균: 3.23
541번 평점 평균: 3.19
542번 평점 평균: 3.76
543번 평점 평균: 4.08
544번 평점 평균: 3.78
545번 평점 평균: 3.48
546번 평점 평균: 3.23
547번 평점 평균: 3.86
548번 평점 평균: 3.09
549번 평점 평균: 3.76
550번 평점 평균: 3.58
551번 평점 평균: 3.82
552번 평점 평균: 3.76
553번 평점 평균: 4.16
554번 평점 평균: 3.

992번 평점 평균: 3.42
993번 평점 평균: 3.34
994번 평점 평균: 4.15
995번 평점 평균: 3.90
996번 평점 평균: 3.94
997번 평점 평균: 3.93
998번 평점 평균: 4.12
999번 평점 평균: 3.19
1000번 평점 평균: 4.13
1001번 평점 평균: 3.65
1002번 평점 평균: 4.14
1003번 평점 평균: 4.14
1004번 평점 평균: 3.16
1005번 평점 평균: 4.14
1006번 평점 평균: 3.07
1007번 평점 평균: 4.22
1008번 평점 평균: 3.84
1009번 평점 평균: 3.83
1010번 평점 평균: 2.48
1011번 평점 평균: 3.70
1012번 평점 평균: 3.36
1013번 평점 평균: 3.85
1014번 평점 평균: 3.49
1015번 평점 평균: 3.73
1016번 평점 평균: 3.79
1017번 평점 평균: 3.25
1018번 평점 평균: 4.16
1019번 평점 평균: 3.01
1020번 평점 평균: 3.99
1021번 평점 평균: 4.69
1022번 평점 평균: 3.56
1023번 평점 평균: 4.07
1024번 평점 평균: 3.70
1025번 평점 평균: 3.76
1026번 평점 평균: 4.00
1027번 평점 평균: 3.83
1028번 평점 평균: 3.97
1029번 평점 평균: 3.20
1030번 평점 평균: 3.58
1031번 평점 평균: 4.07
1032번 평점 평균: 3.94
1033번 평점 평균: 3.29
1034번 평점 평균: 3.48
1035번 평점 평균: 3.82
1036번 평점 평균: 4.32
1037번 평점 평균: 3.58
1038번 평점 평균: 3.93
1039번 평점 평균: 2.89
1040번 평점 평균: 4.24
1041번 평점 평균: 4.32
1042번 평점 평균: 2.76
1043번 평점 평균: 3.92
1044번 평점 평균: 3.76
1045번 평점 평균: 3.54
1046번 평점 평균: 3.88
1047번 평점 평균: 3.88


1450번 평점 평균: 2.99
1451번 평점 평균: 3.90
1452번 평점 평균: 4.15
1453번 평점 평균: 3.57
1454번 평점 평균: 3.86
1455번 평점 평균: 3.75
1456번 평점 평균: 4.05
1457번 평점 평균: 3.95
1458번 평점 평균: 3.99
1459번 평점 평균: 4.05
1460번 평점 평균: 3.04
1461번 평점 평균: 3.34
1462번 평점 평균: 3.50
1463번 평점 평균: 3.59
1464번 평점 평균: 3.68
1465번 평점 평균: 3.74
1466번 평점 평균: 3.63
1467번 평점 평균: 3.53
1468번 평점 평균: 3.52
1469번 평점 평균: 4.06
1470번 평점 평균: 2.69
1471번 평점 평균: 3.81
1472번 평점 평균: 3.60
1473번 평점 평균: 2.97
1474번 평점 평균: 3.78
1475번 평점 평균: 3.90
1476번 평점 평균: 3.76
1477번 평점 평균: 4.06
1478번 평점 평균: 3.94
1479번 평점 평균: 4.10
1480번 평점 평균: 3.40
1481번 평점 평균: 4.38
1482번 평점 평균: 3.23
1483번 평점 평균: 3.10
1484번 평점 평균: 3.61
1485번 평점 평균: 3.91
1486번 평점 평균: 3.58
1487번 평점 평균: 3.22
1488번 평점 평균: 4.10
1489번 평점 평균: 2.44
1490번 평점 평균: 4.10
1491번 평점 평균: 3.25
1492번 평점 평균: 3.21
1493번 평점 평균: 3.75
1494번 평점 평균: 3.80
1495번 평점 평균: 2.62
1496번 평점 평균: 2.86
1497번 평점 평균: 3.86
1498번 평점 평균: 3.83
1499번 평점 평균: 3.94
1500번 평점 평균: 3.90
1501번 평점 평균: 3.73
1502번 평점 평균: 3.40
1503번 평점 평균: 3.51
1504번 평점 평균: 3.64
1505번 평점 평

1946번 평점 평균: 3.86
1947번 평점 평균: 3.95
1948번 평점 평균: 3.11
1949번 평점 평균: 4.18
1950번 평점 평균: 3.52
1951번 평점 평균: 3.02
1952번 평점 평균: 3.49
1953번 평점 평균: 3.79
1954번 평점 평균: 3.93
1955번 평점 평균: 3.55
1956번 평점 평균: 3.12
1957번 평점 평균: 3.94
1958번 평점 평균: 3.27
1959번 평점 평균: 4.51
1960번 평점 평균: 3.87
1961번 평점 평균: 3.55
1962번 평점 평균: 2.67
1963번 평점 평균: 4.18
1964번 평점 평균: 3.64
1965번 평점 평균: 3.12
1966번 평점 평균: 4.36
1967번 평점 평균: 3.54
1968번 평점 평균: 2.76
1969번 평점 평균: 3.82
1970번 평점 평균: 3.58
1971번 평점 평균: 4.27
1972번 평점 평균: 4.41
1973번 평점 평균: 3.84
1974번 평점 평균: 3.76
1975번 평점 평균: 3.84
1976번 평점 평균: 3.89
1977번 평점 평균: 3.63
1978번 평점 평균: 3.47
1979번 평점 평균: 3.11
1980번 평점 평균: 3.48
1981번 평점 평균: 3.03
1982번 평점 평균: 3.43
1983번 평점 평균: 4.14
1984번 평점 평균: 3.57
1985번 평점 평균: 3.58
1986번 평점 평균: 4.59
1987번 평점 평균: 3.62
1988번 평점 평균: 3.52
1989번 평점 평균: 3.33
1990번 평점 평균: 3.86
1991번 평점 평균: 4.29
1992번 평점 평균: 2.92
1993번 평점 평균: 3.75
1994번 평점 평균: 4.10
1995번 평점 평균: 3.90
1996번 평점 평균: 3.99
1997번 평점 평균: 4.08
1998번 평점 평균: 3.87
1999번 평점 평균: 3.82
2000번 평점 평균: 3.79
2001번 평점 평

2440번 평점 평균: 3.43
2441번 평점 평균: 4.07
2442번 평점 평균: 3.86
2443번 평점 평균: 3.38
2444번 평점 평균: 3.34
2445번 평점 평균: 3.54
2446번 평점 평균: 3.87
2447번 평점 평균: 4.21
2448번 평점 평균: 3.88
2449번 평점 평균: 3.81
2450번 평점 평균: 3.33
2451번 평점 평균: 3.05
2452번 평점 평균: 4.10
2453번 평점 평균: 3.53
2454번 평점 평균: 3.42
2455번 평점 평균: 2.69
2456번 평점 평균: 3.15
2457번 평점 평균: 3.17
2458번 평점 평균: 3.50
2459번 평점 평균: 3.75
2460번 평점 평균: 4.12
2461번 평점 평균: 3.74
2462번 평점 평균: 3.54
2463번 평점 평균: 3.22
2464번 평점 평균: 3.80
2465번 평점 평균: 4.31
2466번 평점 평균: 2.92
2467번 평점 평균: 4.41
2468번 평점 평균: 4.21
2469번 평점 평균: 3.71
2470번 평점 평균: 3.35
2471번 평점 평균: 3.16
2472번 평점 평균: 3.60
2473번 평점 평균: 3.84
2474번 평점 평균: 4.25
2475번 평점 평균: 4.05
2476번 평점 평균: 4.16
2477번 평점 평균: 4.48
2478번 평점 평균: 3.55
2479번 평점 평균: 3.85
2480번 평점 평균: 3.87
2481번 평점 평균: 3.91
2482번 평점 평균: 3.50
2483번 평점 평균: 3.90
2484번 평점 평균: 3.37
2485번 평점 평균: 3.67
2486번 평점 평균: 3.81
2487번 평점 평균: 3.70
2488번 평점 평균: 4.20
2489번 평점 평균: 3.40
2490번 평점 평균: 3.55
2491번 평점 평균: 3.04
2492번 평점 평균: 3.76
2493번 평점 평균: 3.53
2494번 평점 평균: 3.00
2495번 평점 평

2914번 평점 평균: 4.46
2915번 평점 평균: 3.76
2916번 평점 평균: 3.67
2917번 평점 평균: 3.53
2918번 평점 평균: 3.61
2919번 평점 평균: 3.77
2920번 평점 평균: 3.46
2921번 평점 평균: 3.28
2922번 평점 평균: 4.54
2923번 평점 평균: 3.95
2924번 평점 평균: 3.96
2925번 평점 평균: 3.84
2926번 평점 평균: 3.28
2927번 평점 평균: 3.79
2928번 평점 평균: 3.84
2929번 평점 평균: 3.93
2930번 평점 평균: 3.45
2931번 평점 평균: 3.63
2932번 평점 평균: 3.93
2933번 평점 평균: 3.78
2934번 평점 평균: 3.31
2935번 평점 평균: 3.42
2936번 평점 평균: 4.29
2937번 평점 평균: 3.53
2938번 평점 평균: 3.88
2939번 평점 평균: 3.78
2940번 평점 평균: 3.55
2941번 평점 평균: 3.46
2942번 평점 평균: 4.47
2943번 평점 평균: 4.40
2944번 평점 평균: 4.22
2945번 평점 평균: 3.84
2946번 평점 평균: 2.84
2947번 평점 평균: 3.71
2948번 평점 평균: 4.04
2949번 평점 평균: 3.75
2950번 평점 평균: 3.15
2951번 평점 평균: 4.23
2952번 평점 평균: 4.21
2953번 평점 평균: 3.20
2954번 평점 평균: 3.94
2955번 평점 평균: 3.24
2956번 평점 평균: 3.48
2957번 평점 평균: 4.45
2958번 평점 평균: 3.02
2959번 평점 평균: 3.97
2960번 평점 평균: 4.03
2961번 평점 평균: 3.98
2962번 평점 평균: 2.90
2963번 평점 평균: 3.97
2964번 평점 평균: 4.54
2965번 평점 평균: 3.59
2966번 평점 평균: 4.06
2967번 평점 평균: 3.46
2968번 평점 평균: 3.79
2969번 평점 평

3403번 평점 평균: 4.14
3404번 평점 평균: 3.81
3405번 평점 평균: 4.12
3406번 평점 평균: 4.05
3407번 평점 평균: 3.50
3408번 평점 평균: 3.77
3409번 평점 평균: 4.20
3410번 평점 평균: 3.22
3411번 평점 평균: 2.73
3412번 평점 평균: 4.16
3413번 평점 평균: 4.11
3414번 평점 평균: 4.10
3415번 평점 평균: 4.01
3416번 평점 평균: 3.58
3417번 평점 평균: 3.87
3418번 평점 평균: 3.79
3419번 평점 평균: 4.03
3420번 평점 평균: 4.35
3421번 평점 평균: 4.33
3422번 평점 평균: 2.66
3423번 평점 평균: 3.94
3424번 평점 평균: 4.20
3425번 평점 평균: 3.54
3426번 평점 평균: 3.98
3427번 평점 평균: 3.76
3428번 평점 평균: 4.00
3429번 평점 평균: 3.60
3430번 평점 평균: 3.42
3431번 평점 평균: 3.81
3432번 평점 평균: 3.28
3433번 평점 평균: 3.02
3434번 평점 평균: 3.63
3435번 평점 평균: 3.83
3436번 평점 평균: 3.80
3437번 평점 평균: 4.50
3438번 평점 평균: 3.55
3439번 평점 평균: 4.10
3440번 평점 평균: 4.26
3441번 평점 평균: 2.91
3442번 평점 평균: 3.44
3443번 평점 평균: 3.92
3444번 평점 평균: 3.10
3445번 평점 평균: 3.88
3446번 평점 평균: 4.47
3447번 평점 평균: 3.86
3448번 평점 평균: 3.62
3449번 평점 평균: 4.17
3450번 평점 평균: 3.60
3451번 평점 평균: 3.87
3452번 평점 평균: 4.46
3453번 평점 평균: 3.37
3454번 평점 평균: 3.50
3455번 평점 평균: 4.04
3456번 평점 평균: 4.42
3457번 평점 평균: 3.52
3458번 평점 평

3893번 평점 평균: 2.58
3894번 평점 평균: 3.76
3895번 평점 평균: 3.30
3896번 평점 평균: 3.14
3897번 평점 평균: 4.10
3898번 평점 평균: 3.74
3899번 평점 평균: 3.58
3900번 평점 평균: 3.59
3901번 평점 평균: 3.55
3902번 평점 평균: 4.89
3903번 평점 평균: 3.33
3904번 평점 평균: 3.91
3905번 평점 평균: 3.91
3906번 평점 평균: 3.66
3907번 평점 평균: 3.58
3908번 평점 평균: 3.69
3909번 평점 평균: 3.41
3910번 평점 평균: 3.59
3911번 평점 평균: 3.64
3912번 평점 평균: 4.48
3913번 평점 평균: 3.66
3914번 평점 평균: 3.64
3915번 평점 평균: 3.65
3916번 평점 평균: 3.89
3917번 평점 평균: 3.65
3918번 평점 평균: 3.31
3919번 평점 평균: 4.07
3920번 평점 평균: 4.13
3921번 평점 평균: 3.93
3922번 평점 평균: 2.78
3923번 평점 평균: 3.78
3924번 평점 평균: 3.94
3925번 평점 평균: 3.97
3926번 평점 평균: 3.91
3927번 평점 평균: 3.94
3928번 평점 평균: 3.18
3929번 평점 평균: 3.03
3930번 평점 평균: 4.26
3931번 평점 평균: 3.51
3932번 평점 평균: 3.94
3933번 평점 평균: 3.88
3934번 평점 평균: 2.61
3935번 평점 평균: 3.42
3936번 평점 평균: 4.35
3937번 평점 평균: 4.27
3938번 평점 평균: 4.17
3939번 평점 평균: 3.71
3940번 평점 평균: 3.68
3941번 평점 평균: 3.02
3942번 평점 평균: 2.66
3943번 평점 평균: 4.22
3944번 평점 평균: 3.54
3945번 평점 평균: 3.42
3946번 평점 평균: 3.73
3947번 평점 평균: 4.12
3948번 평점 평

4359번 평점 평균: 3.62
4360번 평점 평균: 2.58
4361번 평점 평균: 4.17
4362번 평점 평균: 2.95
4363번 평점 평균: 4.33
4364번 평점 평균: 3.24
4365번 평점 평균: 2.55
4366번 평점 평균: 3.46
4367번 평점 평균: 3.54
4368번 평점 평균: 3.69
4369번 평점 평균: 3.73
4370번 평점 평균: 3.67
4371번 평점 평균: 3.61
4372번 평점 평균: 4.04
4373번 평점 평균: 4.09
4374번 평점 평균: 4.34
4375번 평점 평균: 4.06
4376번 평점 평균: 3.81
4377번 평점 평균: 3.64
4378번 평점 평균: 3.15
4379번 평점 평균: 3.10
4380번 평점 평균: 3.66
4381번 평점 평균: 3.42
4382번 평점 평균: 2.88
4383번 평점 평균: 3.40
4384번 평점 평균: 4.00
4385번 평점 평균: 3.26
4386번 평점 평균: 3.60
4387번 평점 평균: 3.10
4388번 평점 평균: 3.81
4389번 평점 평균: 3.30
4390번 평점 평균: 3.09
4391번 평점 평균: 3.68
4392번 평점 평균: 3.44
4393번 평점 평균: 3.90
4394번 평점 평균: 3.52
4395번 평점 평균: 3.33
4396번 평점 평균: 3.68
4397번 평점 평균: 3.43
4398번 평점 평균: 4.15
4399번 평점 평균: 3.18
4400번 평점 평균: 4.15
4401번 평점 평균: 3.68
4402번 평점 평균: 3.68
4403번 평점 평균: 3.97
4404번 평점 평균: 3.07
4405번 평점 평균: 4.47
4406번 평점 평균: 3.99
4407번 평점 평균: 3.29
4408번 평점 평균: 3.77
4409번 평점 평균: 3.72
4410번 평점 평균: 4.00
4411번 평점 평균: 3.90
4412번 평점 평균: 3.37
4413번 평점 평균: 4.00
4414번 평점 평

KeyboardInterrupt: 

In [ ]:
# 각 사용자별 평균 평점이 4점 이상인 사용자 및 인원수 구하기

print('사용자 ID: ', np.unique(data[:,0]))

high_user = []
for user, rate in data[:,[0,2]]:
    for unq_user in np.unique(data[:,0]):
        mn = np.mean(data[data[:,0]==unq_user][:,2])
        if mn >= 4.7:
            high_user.append(unq_user) 
    print(f'평균 평점이 4점 이상인 사용자 목록: {high_user}번')
#         print(f'평균 평점이 4점 이상인 사용자 인원수: {high_user}번')

In [331]:
# A.

# 각 사용자별 평점 평균 구하기 (사용자 ID 수집: ID컬럼에 대한 np.unique() 함수 적용)
user_ids = np.unique(data[:,0])
print(f'전체 사용자 수: {len(user_ids):,}명')

# 리스트 comprehension 이용하기
user_avg_rating = [ [id, np.mean(data[data[:,0]==id][:,2])] for id in user_ids ]

전체 사용자 수: 6,040명


In [332]:
# print(user_avg_rating[:5])
for id, rating in user_avg_rating[:10]:
    print(f'{id} : {rating:.2f}점')

1 : 4.19점
2 : 3.71점
3 : 3.90점
4 : 4.19점
5 : 3.15점
6 : 3.90점
7 : 4.32점
8 : 3.88점
9 : 3.74점
10 : 4.11점


In [334]:
# A.
# 각 사용자별 평균 평점이 4점 이상인 사용자 및 인원수 구하기

# 파이썬 List -> 넘파이 ndarray로 바꿔주기
user_avg_rating = np.array(user_avg_rating)
print(f'평균 평점이 4점 이상인 유저 수: {np.sum(user_avg_rating[:,1] >= 4):,} 명')

평균 평점이 4점 이상인 유저 수: 1,544 명
