[문제-1] 길이가 10인 0-벡터를 만드세요.

In [96]:
import numpy as np

a = np.zeros(10, dtype=int)
print(a)

[0 0 0 0 0 0 0 0 0 0]


[문제-2] 길이가 10이며 다섯번째 원소만 1이고 나머지 원소는 모두 0인 벡터를 만드세요.

In [6]:
a = np.zeros(10, dtype=int)
a[4] = 1
print(a)

[0 0 0 0 1 0 0 0 0 0]


 [문제-3] 10 부터 49까지의 값을 가지는 벡터를 만드세요.

In [106]:
a = np.arange(10,50)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


[문제-4] 위 벡터의 순서를 바꾸세요.

In [107]:
b = a[::-1]
print(b)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [108]:
a = np.arange(49,9,-1)
print(a)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


 [문제-5] 0부터 8까지의 값을 가지는 3x3 행렬을 만드세요.

In [101]:
a = np.arange(0,9).reshape(3,3)
print(a)

# c = np.reshape(a, (3,3))
# print(c)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


[문제-6] 벡터 [1,2,0,0,4,0] 에서 원소의 값이 0이 아닌 원소만 선택한 벡터를 만드세요.

In [109]:
a = np.array([1,2,0,0,4,0])
print(a[a != 0])

[1 2 4]


 [문제-7] 3x3 단위 행렬(identity matrix)을 만드세요

In [34]:
a = np.identity(3) #np.eye(3)
print(a)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


[문제-8] 난수 원소를 가지는 3x3 행렬을 만드세요

In [4]:
import numpy as np
np.random.seed(10)

a = np.random.rand(3,3)
print(a)

[[0.77132064 0.02075195 0.63364823]
 [0.74880388 0.49850701 0.22479665]
 [0.19806286 0.76053071 0.16911084]]


[문제-9] 위에서 만든 난수 행렬에서 최대값/최솟값 원소를 찾으세요.

In [5]:
print('최대값: ',np.amax(a))
print('최소값: ', np.amin(a))

최대값:  0.771320643266746
최소값:  0.0207519493594015


[문제-10] 위에서 만든 난수 행렬에서 행 평균, 열 평균을 계산하세요.

In [31]:
print('행 평균: ', np.mean(a, axis=1))
print('열 평균: ', np.mean(a, axis=0))

[0.47524028 0.49070251 0.37590147]
[0.57272913 0.42659656 0.34251857]


[문제-11] 5x5짜리 정방행렬의 단위행렬을 생성하시오

In [33]:
a = np.identity(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


 [문제-12] 10~50까지 값 9개를 정수로 발생시켜 출력

In [36]:
a = np.random.randint(10, 51, 9)
print(a)

[23 15 23 35 23 38 32 40 40]


[문제-13] '문제-12' 배열의 shape을 3x3으로 변환

In [40]:
b = a.reshape(3,3)
print(b)

[[23 15 23]
 [35 23 38]
 [32 40 40]]


 [문제-14] '문제-13' 배열의 각 행끼리의 합을 구하여 출력

In [41]:
print(np.sum(b, axis=1))

[ 61  96 112]


[문제-15] '문제-13' 배열의 각 열 중 최대값 구하여 출력

In [42]:
print(np.amax(b, axis=0))

[35 40 40]


[문제-16] '문제-13' 배열의 전체 요소의 평균을 구하여 출력

In [43]:
print(np.mean(b))

29.88888888888889


 [문제-17] 1~10 사이의 정수를 요소로 하는 2x3 배열 생성

In [117]:
a = np.random.randint(1,11,(2,3))
print(a)

[[ 8 10  3]
 [ 8  1  8]]


 [문제-18] 10~20 사이의 정수를 요소로 하는 3x2 배열 생성

In [118]:
b = np.random.randint(10,21,(3,2))
print(b)

[[14 19]
 [12 18]
 [18 20]]


 [문제-19] '문제-17'과 '문제-18'의 두 배열의 행렬 곱을 구하여 출력

In [119]:
c = np.matmul(a,b)
print(c)

[[286 392]
 [268 330]]


In [120]:
c = a@b
print(c)

[[286 392]
 [268 330]]


[문제-20] '문제-19' 배열의 전치 행렬을 구하여 출력

In [121]:
print(c.T)
# print(c.transpose())

[[286 268]
 [392 330]]


[문제-21] 로또 번호 생성하기 (1~46 사이의 중복되지 않은 정수 6개 추출)

In [130]:
b = np.random.choice(np.arange(1,47), 6, replace=False)
print(b)

[11 18 14 42 28  4]


In [131]:
a = np.arange(1,47)
b = np.random.choice(a, size = (6,), replace=False)
print(b)

[32 42  4 28 14 24]
